# Pre-production Acceptance Testing (PAT) Environment Configuration
spring:
  datasource:
    url: jdbc:mysql://pat-db-server:3306/OAuthTemplate_PAT?useSSL=true&serverTimezone=UTC
    username: ${PAT_DB_USERNAME}
    password: ${PAT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate  # Validate the schema, don't change the database
    show-sql: false

# PAT environment settings
app:
  security:
    cookie:
      secure: true  # Require HTTPS for cookies
  profile:
    upload-dir: /app/data/uploads/profiles
  cors:
    allowed-origins: https://pat.yourdomain.com

# Logging configuration for PAT
logging:
  level:
    root: WARN
    com.template.OAuth: INFO

# SSL configuration for PAT
server:
  ssl:
    enabled: true
    key-store: classpath:pat-keystore.p12
    key-store-password: ${PAT_SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat