# Production Environment Configuration
spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/OAuthTemplate_Prod?useSSL=true&serverTimezone=UTC
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate  # Validate the schema, don't change the database
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Production environment settings
app:
  security:
    cookie:
      secure: true  # Require HTTPS for cookies
      same-site: strict
    jwt:
      expiration: 1800000  # 30 minutes
    refresh:
      expiration: 2592000000  # 30 days
  profile:
    upload-dir: /app/data/uploads/profiles
  cors:
    allowed-origins: https://www.yourdomain.com

# Logging configuration for production (minimal)
logging:
  level:
    root: WARN
    com.template.OAuth: INFO
  file:
    name: /var/log/oauth-app/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# SSL configuration for production
server:
  ssl:
    enabled: true
    key-store: classpath:prod-keystore.p12
    key-store-password: ${PROD_SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
  http2:
    enabled: true