# Common configuration shared across all profiles
spring:
  config:
    import: optional:file:.env[.properties]  # Load environment variables
  profiles:
    active: dev  # Default profile is development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email

#          spotify:
#            client-id: ${SPOTIFY_CLIENT_ID}
#            client-secret: ${SPOTIFY_CLIENT_SECRET}
#
#          apple:
#            client-id: ${APPLE_CLIENT_ID}
#            client-secret: ${APPLE_CLIENT_SECRET}
#
#          soundcloud:
#            client-id: ${SOUNDCLOUD_CLIENT_ID}
#            client-secret: ${SOUNDCLOUD_CLIENT_SECRET}

server:
  port: 8080
  forward-headers-strategy: framework

# Common application settings
app:
  security:
    jwt:
      expiration: 3600000         # JWT token expiration time in milliseconds (1 hour)
    refresh:
      expiration: 604800000       # Refresh token expiration time (7 days)
  profile:
    max-bio-length: 500           # Maximum biography length in characters
    default-theme: SYSTEM         # Default theme preference


# Replace your current springdoc configuration with this
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    csrf:
      enabled: true
    try-it-out-enabled: true
    filter: true
    syntax-highlight:
      activated: true
    deepLinking: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-actuator: false
  packages-to-scan: com.template.OAuth.controller
  paths-to-match: /api/**, /auth/**, /refresh-token

# Actuator Configuration (add to your application.yaml)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,env,mappings
      base-path: /management
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
      roles: ADMIN
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name:oauth-template}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
  prometheus:
    metrics:
      export:
        enabled: true

# Custom application info
info:
  application:
    name: OAuth Template
    description: OAuth 2.0 Authentication Service
    version: 0.0.1-SNAPSHOT
    environment: ${spring.profiles.active:dev}