# Development Environment Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OAuthTemplate?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Cookie settings for development
app:
  security:
    cookie:
      secure: false  # Allows cookies over HTTP in dev
  profile:
    upload-dir: uploads/profiles/dev
  cors:
    allowed-origins: http://localhost:3000

# Logging configuration for development (more verbose)
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.template.OAuth: DEBUG
    org.hibernate.SQL: DEBUG
    com.template.OAuth.service.AuditService: DEBUG

# Disable caching for templates and static resources
spring.thymeleaf.cache: false
spring.resources.cache.period: 0

