# Testing Environment Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OAuthTemplate_Test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recreate the schema for each test run
    show-sql: true

# Test environment settings
app:
  security:
    cookie:
      secure: false  # Allows cookies over HTTP in test
  profile:
    upload-dir: uploads/profiles/test
  cors:
    allowed-origins: http://localhost:3000

# Logging configuration for testing
logging:
  level:
    root: INFO
    com.template.OAuth: DEBUG
    com.template.OAuth.service.AuditService: DEBUG

# Disable OAuth for testing
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-client-id
            client-secret: test-client-secret

# Test-specific properties (for testing only)
jwt:
  secret: test-secret-key-for-unit-testing