spring:
  config:
    import: optional:file:.env[.properties]  # Load environment variables
  datasource:
    url: jdbc:mysql://localhost:3306/OAuthTemplate?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    generate-ddl: true
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email

#          spotify:
#            client-id: ${SPOTIFY_CLIENT_ID}
#            client-secret: ${SPOTIFY_CLIENT_SECRET}
#
#          apple:
#            client-id: ${APPLE_CLIENT_ID}
#            client-secret: ${APPLE_CLIENT_SECRET}
#
#          soundcloud:
#            client-id: ${SOUNDCLOUD_CLIENT_ID}
#            client-secret: ${SOUNDCLOUD_CLIENT_SECRET}

server:
  port: 8080
  forward-headers-strategy: framework # ✅ Ensures correct forwarding headers

# Logging configuration for debugging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.cors: DEBUG