# Common configuration shared across all profiles
spring:
  profiles:
    active: dev  # Default profile is development
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/OAuthTemplate?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
    rate-limiting:
      enabled: true
      # General API requests per minute per IP
      default-limit: 100
      # Authentication endpoints requests per minute per IP
      auth-limit: 100
      # Sensitive operations requests per minute per IP
      sensitive-limit: 3
      # Time in minutes to block IP after too many failed attempts
      block-duration-minutes: 30
      # Number of failed attempts before blocking IP
      max-failed-attempts: 5

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

# Common application settings
app:
  security:
    jwt:
      secret: ${JWT_SECRET:defaultsecretkey12345678901234567890}
      expiration: 3600000         # JWT token expiration time in milliseconds (1 hour)
    refresh:
      expiration: 604800000       # Refresh token expiration time (7 days)
    verification:
      expirationHours: 24         # Email verification token expiration time in hours
    passwordReset:
      expirationHours: 1          # Password reset token expiration time in hours
    cookie:
      secure: false               # Allows cookies over HTTP in dev (set to true in production)
      sameSite: lax
  profile:
    max-bio-length: 500           # Maximum biography length in characters
    default-theme: SYSTEM         # Default theme preference
    upload-dir: ${UPLOAD_DIR:uploads/profiles}  # Profile picture upload directory
  email:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:email@example.com}
    password: ${EMAIL_PASSWORD:password}
    fromAddress: ${EMAIL_FROM_ADDRESS:no-reply@example.com}
    fromName: ${EMAIL_FROM_NAME:OAuth Template App}
    debug: ${EMAIL_DEBUG:false}
  application:
    baseUrl: ${APP_BASE_URL:http://localhost:3000}
    supportEmail: ${SUPPORT_EMAIL:support@example.com}
    name: ${APP_NAME:OAuth Template}
  cors:
    allowedOrigins:
      - ${FRONTEND_URL:http://localhost:3000}
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  login-success-redirect-url: ${LOGIN_SUCCESS_REDIRECT_URL:/home}
  admin-emails: ${ADMIN_EMAILS:admin@example.com}

# Springdoc configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    csrf:
      enabled: true
    try-it-out-enabled: true
    filter: true
    syntax-highlight:
      activated: true
    deepLinking: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-actuator: false
  packages-to-scan: com.template.OAuth.controller
  paths-to-match: /api/**, /auth/**, /refresh-token

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,env,mappings
      base-path: /management
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
      roles: ADMIN
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name:oauth-template}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
  prometheus:
    metrics:
      export:
        enabled: true

# Custom application info
info:
  application:
    name: ${APP_NAME:OAuth Template}
    description: OAuth 2.0 Authentication Service
    version: 0.0.1-SNAPSHOT
    environment: ${spring.profiles.active:dev}