version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.${SPRING_PROFILES_ACTIVE:-dev}
      args:
        - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    container_name: oauth-app-${SPRING_PROFILES_ACTIVE:-dev}
    env_file:
      - ../../.env.${SPRING_PROFILES_ACTIVE:-dev}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    ports:
      - "${SERVER_PORT:-8080}:8080"
    volumes:
      - oauth-uploads-${SPRING_PROFILES_ACTIVE:-dev}:/app/data/uploads
      - oauth-logs-${SPRING_PROFILES_ACTIVE:-dev}:/var/log/oauth-app
    networks:
      - oauth-network-${SPRING_PROFILES_ACTIVE:-dev}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/management/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  db:
    image: mysql:8.0
    container_name: oauth-db-${SPRING_PROFILES_ACTIVE:-dev}
    restart: unless-stopped
    env_file:
      - ../../.env.${SPRING_PROFILES_ACTIVE:-dev}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=oauth_${SPRING_PROFILES_ACTIVE:-dev}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - oauth-mysql-data-${SPRING_PROFILES_ACTIVE:-dev}:/var/lib/mysql
      - ../../docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - oauth-network-${SPRING_PROFILES_ACTIVE:-dev}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  oauth-network-${SPRING_PROFILES_ACTIVE:-dev}:
    driver: bridge

volumes:
  oauth-uploads-${SPRING_PROFILES_ACTIVE:-dev}:
  oauth-logs-${SPRING_PROFILES_ACTIVE:-dev}:
  oauth-mysql-data-${SPRING_PROFILES_ACTIVE:-dev}: